// =====================================================================
// VM ROLE DEFINITIONS
// =====================================================================
// Each step now carries a `context` object with 4 educational fields:
//   what:     What is this step and what to do here
//   industry: What real-world industry practice this step replicates
//   output:   What the operator produces / records from this step
//   learning: What the student learns from completing this step
// =====================================================================

const ROLES = [
  {
    key: 'dispensing',
    order: 1,
    stageName: 'Dispensing',
    title: 'Dispensing Operator',
    icon: 'weight',
    summary: 'Weighs and releases raw materials (API, Excipient, Binder) for the batch.',
    steps: [
      {
        key: 'receive',
        type: 'info',
        label: 'Receive Batch Instruction',
        text: 'Batch instruction received.\nAPI: 10.00 kg\nExcipient: 50.00 kg\nBinder: 5.00 kg',
        context: {
          what: 'Read the master batch instruction card which specifies the exact quantities of each raw material required for this production run.',
          industry: 'Replicates the GMP-mandated "Batch Manufacturing Record (BMR)" handover — a documented order signed by the Production Pharmacist before any weighing begins, as required by 21 CFR Part 211.101.',
          output: 'A confirmed understanding of the three target quantities (API: 10 kg, Excipient: 50 kg, Binder: 5 kg) that will govern the entire weighing sequence.',
          learning: 'You learn that every pharmaceutical batch begins with a formal, traceable instruction — not verbal orders — to prevent misinterpretation of quantities.',
        },
      },
      {
        key: 'identify',
        type: 'select',
        label: 'Identify Material',
        field: 'material',
        options: [
          { value: 'API', label: 'API', target: 10, unit: 'kg' },
          { value: 'Excipient', label: 'Excipient', target: 50, unit: 'kg' },
          { value: 'Binder', label: 'Binder', target: 5, unit: 'kg' },
        ],
        context: {
          what: "Select which raw material container you are about to weigh. This links the scale's target to the correct quantity for that specific ingredient.",
          industry: "Mirrors the barcode verification / RFID label check step required by cGMP. In a real facility the operator scans the container label and the LIMS (Lab Information Management System) automatically sets the scale target.",
          output: "The scale controller's target limit is automatically set to the correct weight for the selected material, preventing a 50 kg target being applied to a 10 kg API lot.",
          learning: 'You understand why materials must be identified one at a time — mixing up containers (e.g., dispensing 50 kg of API instead of Excipient) would cause a lethal dosage error in the final tablets.',
        },
      },
      {
        key: 'load',
        type: 'load',
        label: 'Load Material',
        text: 'Load the identified material onto the dispensing scale.',
        context: {
          what: 'Physically place the raw material container onto the calibrated dispensing balance / weigh scale before starting the transfer.',
          industry: 'Replicates the GMP step where the container is checked for correct labelling, integrity (no tears, leaks), expiry date, and then placed on an IQ/OQ/PQ-validated balance.',
          output: "The scale registers the container's gross weight, ready for taring and net weight measurement.",
          learning: 'You learn the importance of using validated, calibrated equipment — an uncalibrated scale could weigh out the wrong quantity, causing batch failure or patient harm.',
        },
      },
      {
        key: 'set_target',
        type: 'set',
        label: 'Set / Confirm Target Quantity',
        field: 'targetQty',
        unit: 'kg',
        fromSelectTarget: true,
        context: {
          what: "Enter or confirm the target weight on the scale's PLC controller. This value is pulled from the batch instruction and linked to the material you identified in the previous step.",
          industry: "In industry, this step programs the scale's electronic weight controller (e.g., Mettler Toledo ICS series) with the planned weight. An alarm will trigger if dispensing goes above or below the set limit.",
          output: "The scale's digital controller is programmed with the exact target (e.g., 10.00 kg) and its validated ±2% tolerance band (9.80–10.20 kg).",
          learning: 'You learn that setting the target is a safety gate — the machine will refuse to proceed if the tolerance is exceeded, which is what triggers the Quality Alert system.',
        },
      },
      {
        key: 'start',
        type: 'start',
        label: 'Start Dispensing',
        context: {
          what: 'Activate the vacuum transfer or start manually pouring the material onto the scale. The feeder will slow down as it approaches the target weight.',
          industry: 'Replicates the vacuum powder transfer system (e.g., Volkmann or Piab vacuum conveyor) that pneumatically moves powder from a drum to the weigh vessel in a dust-controlled dispensing booth.',
          output: 'Material begins flowing. The live weight reading climbs in real time on the HMI/scale display.',
          learning: 'You experience how modern pharmaceutical manufacturing uses closed, contained powder transfer to protect both the operator (inhalation risk) and the product (contamination risk).',
        },
      },
      {
        key: 'monitor',
        type: 'monitor',
        label: 'Monitor Weight',
        field: 'liveWeight',
        unit: 'kg',
        durationMs: 3000,
        context: {
          what: 'Watch the live scale reading climb towards the target. The system simulates the real-time weight readout as material is transferred.',
          industry: 'Replicates the HMI (Human-Machine Interface) display on the dispensing balance in a real GMP dispensing suite. The operator watches for overshoot (adding too much), which requires a corrective deviation report.',
          output: 'A real-time weight trend that settles at the target value ± any natural variation from material flow.',
          learning: 'You learn that scale monitoring is an active, not passive, task. Inattention during this step can allow overshoot that results in either wastage or a quality deviation.',
        },
      },
      {
        key: 'confirm',
        type: 'confirm',
        label: 'Confirm Actual Quantity',
        field: 'actualQty',
        unit: 'kg',
        compareTo: 'targetQty',
        tolerancePct: 2,
        context: {
          what: 'Enter the final actual weight shown on the scale after the feeder stops. This is the value that is permanently written into the electronic batch record.',
          industry: 'In GMP manufacturing this is the "weighed quantity entry" in the Electronic Batch Record (EBR). Any entry outside the ±2% tolerance automatically raises a Process Deviation and puts the material on Hold, requiring QMS review.',
          output: 'A signed-off weight entry in the EBR. If within tolerance: proceed. If outside ±2%: a quality alarm fires and the QMS Monitor is immediately notified.',
          learning: 'This step shows the difference between the "target" (the plan) and the "actual" (reality). You learn that real manufacturing requires documenting what actually happened, not what was planned.',
        },
      },
      {
        key: 'record',
        type: 'record',
        label: 'Record Result',
        context: {
          what: "Review and accept the summary log of this material's dispensing step. The system records the operator ID, timestamp, target vs. actual weight, and pass/fail status.",
          industry: 'Replicates the GMP "Data Integrity" requirement (ALCOA+ principles: Attributable, Legible, Contemporaneous, Original, Accurate). Every data point must be recorded at the time of the activity.',
          output: "A completed, time-stamped electronic dispensing record entry with the operator's digital signature.",
          learning: 'You understand that pharmaceutical audit trails are not optional — they are a regulatory requirement. If a batch is recalled years later, regulators trace every entry back to the original operator.',
        },
      },
      {
        key: 'release',
        type: 'complete',
        label: 'Release Material to Next Process',
        context: {
          what: 'Seal and label the weighed container, then formally transfer it down the production pipeline to the Milling stage. This action completes the Dispensing stage.',
          industry: 'Replicates the in-process material transfer ticket — a physical label attached to the container specifying: product, batch number, quantity, and the stage it is being transferred to.',
          output: 'The Dispensing stage is marked complete, the Milling Operator station is unlocked, and the material formally enters the next stage of the manufacturing process.',
          learning: 'You learn that each manufacturing stage is a controlled handover — material cannot move to the next step without a documented, signed release from the previous operator.',
        },
      },
    ],
  },

  {
    key: 'milling',
    order: 2,
    stageName: 'Milling',
    title: 'Milling / Sieving Operator',
    icon: 'grinder',
    summary: 'Mills dispensed material to target particle size and screen.',
    steps: [
      {
        key: 'load',
        type: 'load',
        label: 'Load Mill',
        text: 'Load the dispensed material into the mill.',
        context: {
          what: "Transfer the dispensed raw material from the dispensing containers into the mill's feed hopper.",
          industry: 'Replicates loading a hammer mill or quadro comil (conical mill) which are the industry-standard machines for particle size reduction in pharma manufacturing.',
          output: 'The mill is loaded with the correct batch of material, ready for size reduction.',
          learning: 'You learn that controlled feeding of material into a mill prevents bridging (blockage) and ensures uniform processing.',
        },
      },
      {
        key: 'set_rpm',
        type: 'set',
        label: 'Set RPM',
        field: 'rpm',
        unit: 'RPM',
        target: 1500,
        context: {
          what: 'Set the rotational speed (RPM) of the mill. Higher RPM gives finer particle size but generates more frictional heat.',
          industry: 'In a real Quadro Comil, RPM directly controls the impeller speed. The validated process RPM for each product is documented in the Process Validation report and cannot be changed without a formal Change Control.',
          output: 'The mill is programmed to run at 1500 RPM — the validated speed for Paracetamol particle size reduction to 250 µm.',
          learning: "RPM vs. particle size is a critical process parameter (CPP). You learn that changing speed changes the drug's dissolution profile — and ultimately how fast the tablet works in a patient's body.",
        },
      },
      {
        key: 'select_screen',
        type: 'select',
        label: 'Select Screen',
        field: 'screen',
        options: [
          { value: '40 mesh', label: '40 mesh' },
          { value: '60 mesh', label: '60 mesh' },
          { value: '80 mesh', label: '80 mesh' },
        ],
        context: {
          what: 'Select the correct mesh screen for the mill. The mesh number defines the maximum particle size that passes through.',
          industry: 'Screen selection is a defined parameter in the validated process. For Paracetamol 500 mg tablets, a 60-mesh screen (250 µm opening) gives the optimal particle size for granulation binding.',
          output: 'The mill is fitted with the 60-mesh screen, ensuring no particle larger than 250 µm passes to the next stage.',
          learning: 'Particle size directly affects tablet hardness, dissolution rate, and content uniformity. The wrong screen can cause a batch failure at the final dissolution test.',
        },
      },
      {
        key: 'set_time',
        type: 'set',
        label: 'Set Processing Time',
        field: 'processingTime',
        unit: 'sec',
        target: 60,
        context: {
          what: "Set the total milling duration. The mill will automatically stop after this time, even if material remains in the hopper.",
          industry: 'Milling time is a process limit set during development. Over-milling generates excessive fines (very small particles) which cause poor flow and compressibility issues downstream.',
          output: "A fixed 60-second processing window is programmed into the mill's PLC controller.",
          learning: 'You learn that time-limiting a process is a quality safeguard — it prevents operators from running equipment beyond validated limits even with the best intentions.',
        },
      },
      {
        key: 'start',
        type: 'start',
        label: 'Start',
        context: {
          what: 'Start the mill. The impeller begins rotating and material is drawn through the screen.',
          industry: 'In an industry setting, the start command is only possible after all safety interlocks are satisfied: the screen is fitted, guards are locked, and the OEE (Overall Equipment Effectiveness) system logs the start timestamp.',
          output: 'The mill runs at target RPM. Live temperature and RPM data begin streaming to the HMI.',
          learning: 'This step shows that in pharmaceutical manufacturing, machines do not simply "start" — they start a traceable, logged process event.',
        },
      },
      {
        key: 'monitor',
        type: 'monitor',
        label: 'Monitor RPM / Temperature / Time',
        field: 'temperature',
        unit: '°C',
        target: 25,
        durationMs: 4000,
        watchesDefect: true,
        context: {
          what: 'Watch the mill\'s live telemetry: RPM stability, friction-generated temperature, and elapsed time. This is the critical observation window — a temperature rise indicates a mechanical issue.',
          industry: 'This replicates the real-world process deviation scenario: a worn screen mesh or seized bearing causes friction, raising the mill temperature above the 25°C ± 2°C validated limit and degrading the heat-sensitive Paracetamol API.',
          output: 'Live temperature readings. If the temperature exceeds 27°C, a Process Deviation alarm fires and both the VM panel and the QMS Monitor are immediately notified.',
          learning: 'You learn to distinguish between normal process variation and a genuine quality event. This is the key skill of a Pharmaceutical Manufacturing Operator — recognizing deviations before they damage the product.',
        },
      },
      {
        key: 'complete',
        type: 'record',
        label: 'Complete',
        context: {
          what: 'Log the milling completion and all final process parameters (achieved RPM, peak temperature, total time) into the batch record.',
          industry: 'The "process completion log" is a mandatory section of the BMR. It must be completed contemporaneously (at the time of the activity), not filled in later.',
          output: 'A signed process completion record with all critical parameters documented.',
          learning: 'Real-time data capture is a GMP requirement under ALCOA+. Retrospective data entry is a regulatory violation.',
        },
      },
      {
        key: 'transfer',
        type: 'complete',
        label: 'Transfer Material',
        context: {
          what: 'Formally transfer the milled material to the Granulation stage. This closes the Milling stage.',
          industry: 'Replicates the in-process material yield calculation — the operator weighs the milled output and calculates the process yield. A yield < 98% triggers a deviation investigation.',
          output: 'Milled material is confirmed transferred to the next stage. The Granulation Operator station is unlocked.',
          learning: 'Yield tracking is how the industry ensures no material is lost without explanation — it detects theft, spills, and processing errors before the batch reaches patients.',
        },
      },
    ],
  },

  {
    key: 'granulation',
    order: 3,
    stageName: 'Granulation',
    title: 'Granulation Operator',
    icon: 'droplet',
    summary: 'Adds binder to milled powder and forms wet granules.',
    steps: [
      {
        key: 'load',
        type: 'load',
        label: 'Load Powder',
        text: 'Load the milled material into the granulator.',
        context: {
          what: 'Transfer the milled powder into the High Shear Wet Granulator (HSWG) bowl.',
          industry: 'Replicates loading a pharmaceutical-grade HSWG (e.g., Diosna P-VAC or Fielder PMA series). The bowl must be clean, dry, and verified by a second operator before loading.',
          output: 'The granulator bowl is loaded with milled Paracetamol powder, ready for wet granulation.',
          learning: 'Granulation transforms powder particles into larger, more uniform granules — dramatically improving the flowability and compressibility needed for tablet pressing.',
        },
      },
      {
        key: 'add_binder',
        type: 'load',
        label: 'Add Binder',
        text: 'Add the binder solution to the granulator.',
        context: {
          what: 'Add the pre-prepared PVP (Polyvinylpyrrolidone) binder solution through the spray nozzle or manually pour it into the rotating bowl.',
          industry: 'The binder solution is prepared by the lab to a defined concentration (e.g., 5% w/v PVP in purified water) and its volume is calculated to achieve the target moisture level in the granule mass.',
          output: 'Binder solution is added to the milled powder, initiating the granulation reaction.',
          learning: "Binder type and concentration are Critical Process Parameters. Too little binder creates fragile granules that break during compression. Too much creates hard, slow-dissolving tablets that fail dissolution testing.",
        },
      },
      {
        key: 'set_speed',
        type: 'set',
        label: 'Set Speed',
        field: 'speed',
        unit: 'RPM',
        target: 120,
        context: {
          what: 'Set the impeller and chopper speeds on the HSWG. These speeds control the mixing energy applied to the powder-binder mixture.',
          industry: 'Impeller speed in a HSWG directly affects granule size and density. The validated speed for this product is 120 RPM (impeller) to achieve the 500–1000 µm target granule size.',
          output: 'The HSWG is set to the validated mixing speed, ensuring consistent granule formation across every batch.',
          learning: 'Scale-up is one of the hardest challenges in pharma manufacturing — a speed that works in a 10 L lab granulator may not work the same way in a 600 L production unit.',
        },
      },
      {
        key: 'set_binder_flow',
        type: 'set',
        label: 'Set Binder Flow',
        field: 'binderFlow',
        unit: 'mL/min',
        target: 20,
        context: {
          what: 'Set the binder spray rate for controlled addition of the binder solution into the rotating powder mass.',
          industry: 'Rapid binder addition creates lumps (over-granulation). Too slow causes dry granule formation. The validated 20 mL/min rate is an endpoint from process development studies.',
          output: 'A precisely controlled binder addition rate is programmed, ensuring reproducible granule growth kinetics.',
          learning: 'Process parameters are not arbitrary — every number has been determined through Design of Experiments (DoE) studies to optimise the final product quality.',
        },
      },
      {
        key: 'start',
        type: 'start',
        label: 'Start Granulation',
        context: {
          what: 'Start the HSWG. The impeller mixes the powder while binder is sprayed in at the set rate.',
          industry: 'The HSWG start initiates automatic data logging (power consumption, impeller torque, temperature) for Process Analytical Technology (PAT) monitoring per ICH Q8.',
          output: 'Granulation begins. The powder mass progressively transforms into wet granules as binder is added.',
          learning: 'Modern pharmaceutical granulation is moving towards PAT — using real-time measurements (torque, near-infrared spectroscopy) to determine the granulation endpoint instead of fixed time.',
        },
      },
      {
        key: 'monitor',
        type: 'monitor',
        label: 'Monitor',
        field: 'temperature',
        unit: '°C',
        target: 27,
        durationMs: 3000,
        context: {
          what: "Monitor the bowl temperature during granulation. Excessive heat can degrade the API and alter the binder's performance.",
          industry: "Bowl temperature rise during HSWG is caused by the friction of mixing. The validated limit for Paracetamol granulation is 30°C — above this the PVP binder may degrade.",
          output: 'Live temperature telemetry confirming the granulation is running within the validated thermal range.',
          learning: 'You learn that monitoring is not just "watching" — it is a critical quality step that generates data for the permanent batch record.',
        },
      },
      {
        key: 'complete',
        type: 'record',
        label: 'Complete',
        context: {
          what: 'Record the final granulation parameters and the visual endpoint assessment (wet mass consistency).',
          industry: 'Granulation endpoint is traditionally assessed by the operator feeling the wet mass — a skill called "wet mass consistency assessment." Modern facilities use impeller torque as an objective endpoint indicator.',
          output: 'A documented granulation completion record including achieved endpoint, temperature, and binder volume added.',
          learning: 'Granulation is one of the most operator-skill-dependent steps in tablet manufacturing — which is why modern pharma is adopting PAT to replace subjective human judgment.',
        },
      },
      {
        key: 'transfer',
        type: 'complete',
        label: 'Transfer Granules',
        context: {
          what: 'Discharge the wet granules from the HSWG bowl and transfer to the Drying stage.',
          industry: 'Wet granules must be transferred to the dryer immediately after the endpoint — leaving them in the bowl causes further granule growth (over-granulation) and lump formation.',
          output: 'Wet granules are confirmed transferred to the Fluidised Bed Dryer. The Drying Operator station is unlocked.',
          learning: 'Time between granulation and drying is a process parameter — another example of how each step in pharmaceutical manufacturing has specifications that govern the transitions between stages.',
        },
      },
    ],
  },

  {
    key: 'drying',
    order: 4,
    stageName: 'Drying',
    title: 'Drying Operator',
    icon: 'wind',
    summary: 'Dries wet granules to target moisture content.',
    steps: [
      {
        key: 'load',
        type: 'load',
        label: 'Load Wet Granules',
        text: 'Load wet granules into the dryer.',
        context: {
          what: "Transfer the wet granules from the HSWG bowl into the Fluidised Bed Dryer (FBD) product bowl.",
          industry: 'Replicates the FBD loading step using a vacuum transfer system that sucks the wet granule mass from the HSWG directly into the FBD product bowl without operator contact.',
          output: 'The FBD product bowl is filled with wet granules, ready for hot-air fluidised drying.',
          learning: 'Closed-system transfers eliminate cross-contamination risk and reduce operator exposure to potent active ingredients.',
        },
      },
      {
        key: 'set_temp',
        type: 'set',
        label: 'Set Temperature',
        field: 'temperature',
        unit: '°C',
        target: 55,
        context: {
          what: 'Set the inlet air temperature of the FBD. Hot air at this temperature flows through the granule bed, evaporating moisture.',
          industry: 'The FBD inlet temperature is a validated parameter. For Paracetamol, 55°C is used — high enough to dry efficiently but low enough to prevent API degradation (Paracetamol degrades above 80°C).',
          output: 'The FBD is programmed to deliver 55°C inlet air for efficient moisture removal.',
          learning: 'Temperature selection during drying is a stability question — using a temperature that is too high can chemically degrade the drug substance, rendering the entire batch subpotent.',
        },
      },
      {
        key: 'set_airflow',
        type: 'set',
        label: 'Set Airflow',
        field: 'airflow',
        unit: 'm3/h',
        target: 1200,
        context: {
          what: 'Set the air volume flow rate through the FBD. Airflow determines whether the granule bed is properly fluidised (suspended in air) for even drying.',
          industry: 'If airflow is too low, granules settle and dry unevenly. Too high and they are blown out of the product bowl into the exhaust filters. The 1200 m³/h target was determined during process development.',
          output: 'The FBD fan speed is set to deliver uniform fluidisation of the granule bed at the validated airflow rate.',
          learning: 'Fluidisation requires balancing airflow against granule density — a skill that operators develop through experience and that engineers encode into validated process parameters.',
        },
      },
      {
        key: 'set_time',
        type: 'set',
        label: 'Set Drying Time',
        field: 'dryingTime',
        unit: 'min',
        target: 20,
        context: {
          what: 'Set the maximum drying time. The FBD may stop earlier if the target moisture content is reached.',
          industry: 'Modern FBDs use inline NIR (Near Infrared) probes to measure moisture in real-time and stop automatically when the target of ≤2% LOD (Loss on Drying) is achieved.',
          output: 'A maximum 20-minute drying window is set as a safety limit to prevent over-drying.',
          learning: 'Over-dried granules become brittle and produce excessive fines during blending, reducing tablet quality. Under-dried granules cause microbial growth and physical instability.',
        },
      },
      {
        key: 'start',
        type: 'start',
        label: 'Start',
        context: {
          what: 'Start the FBD. Heated, filtered air flows upward through the product bowl, suspending and drying the granules.',
          industry: 'FBD startup follows a documented sequence: inlet air heating check, fan pre-start, bag filter shake-down, then feed air. This sequence is enforced by the PLC to prevent equipment damage.',
          output: 'Fluidised bed drying commences. Granule moisture begins dropping as warm air removes water.',
          learning: "Startup sequences in pharmaceutical equipment are qualification-tested (OQ — Operational Qualification) and cannot be bypassed without invalidating the equipment's regulatory status.",
        },
      },
      {
        key: 'monitor',
        type: 'monitor',
        label: 'Monitor Temperature / Airflow / Moisture',
        field: 'moisture',
        unit: '%',
        target: 3.2,
        durationMs: 3500,
        context: {
          what: 'Monitor the outlet air temperature and moisture content as the drying progresses. The outlet temperature rises as the granules dry out.',
          industry: 'The "exhaust air temperature rise" is the classic drying endpoint indicator. When exhaust temperature approaches inlet temperature, granules are dry. Modern PAT replaces this with inline NIR.',
          output: 'Live moisture and temperature telemetry showing the drying curve until the target ≤3.2% moisture is achieved.',
          learning: 'You learn that drying is a thermodynamic process — the relationship between inlet/outlet temperature and moisture content is predictable and measurable, enabling real-time quality control.',
        },
      },
      {
        key: 'complete',
        type: 'record',
        label: 'Complete',
        context: {
          what: 'Record the final LOD (Loss on Drying) measurement, achieved temperature, actual drying time, and any observations about the dried granule appearance.',
          industry: 'The LOD result is formally entered into the BMR. An offline LOD sample is taken by the QC lab and must agree with the inline reading within ±0.5% before the batch can proceed.',
          output: 'A documented drying record with moisture content result conforming to the specification of ≤3.5% LOD.',
          learning: 'In-process testing (IPT) by QC is a parallel quality check on the operator data — showing that manufacturing quality is not self-certified; it requires independent verification.',
        },
      },
      {
        key: 'transfer',
        type: 'complete',
        label: 'Transfer Dry Granules',
        context: {
          what: 'Discharge the dried granules from the FBD and formally transfer them to the Blending stage.',
          industry: 'Dried granules are typically discharged through a mill (delumper) to break up any aggregates formed during drying before blending.',
          output: 'Dry granules are confirmed transferred to the blender. The Blending Operator station is unlocked.',
          learning: "Process continuity — each stage's output becomes the next stage's raw material. This pipeline structure is why a quality failure at any stage affects all subsequent stages.",
        },
      },
    ],
  },

  {
    key: 'blending',
    order: 5,
    stageName: 'Blending',
    title: 'Blending Operator',
    icon: 'blend',
    summary: 'Blends dried granules with remaining excipients/lubricant.',
    steps: [
      {
        key: 'load',
        type: 'load',
        label: 'Load Material',
        text: 'Load dried granules into the blender.',
        context: {
          what: 'Transfer the dried granules into the blender drum. The blender tumbles the material to achieve a uniform distribution of all components.',
          industry: 'Pharmaceutical blending typically uses a Bin Blender or Tumble Blender (V-blender, double-cone). The blender itself may be the same IBC (Intermediate Bulk Container) used for transport.',
          output: 'The blender is loaded with dried granules, ready for the addition of lubricants and final blending.',
          learning: 'Blending is the last opportunity to correct any content uniformity issues from granulation. Poor blending leads to tablet-to-tablet potency variation, which is a critical quality attribute.',
        },
      },
      {
        key: 'add_ingredients',
        type: 'load',
        label: 'Add Required Ingredients',
        text: 'Add remaining excipients / lubricant.',
        context: {
          what: 'Add the pre-weighed extra-granular components: typically Magnesium Stearate (lubricant), Croscarmellose Sodium (super-disintegrant), and Colloidal Silicon Dioxide (glidant).',
          industry: "Lubricants (especially Magnesium Stearate) are over-sensitive to blending — too much mixing time after adding the lubricant coats the granules in a hydrophobic film, drastically slowing dissolution. This is why lubricants are added last.",
          output: 'All formulation components are present in the blender in the correct ratios.',
          learning: 'Over-lubrication is one of the most common manufacturing errors causing dissolution failures. You learn why lubricant addition is a tightly controlled, time-limited step.',
        },
      },
      {
        key: 'set_rpm',
        type: 'set',
        label: 'Set RPM',
        field: 'rpm',
        unit: 'RPM',
        target: 18,
        context: {
          what: "Set the blender's rotation speed. Low speed is used to gently tumble the mixture without generating fines.",
          industry: 'The 18 RPM target is determined by process validation to achieve uniformity within the validated 60-second blend time. Higher speeds can cause granule attrition (breakdown into fines).',
          output: 'The blender is programmed to rotate at 18 RPM — a gentle mixing speed that preserves granule integrity.',
          learning: 'Process parameters like RPM are counterintuitively low in blending — gentle and consistent mixing outperforms aggressive mixing for final blend uniformity.',
        },
      },
      {
        key: 'set_time',
        type: 'set',
        label: 'Set Mixing Time',
        field: 'mixTime',
        unit: 'sec',
        target: 60,
        context: {
          what: 'Set the blending duration. The blender runs for this exact time, then stops automatically.',
          industry: 'Over-mixing (especially after lubricant addition) is a documented quality risk. The 60-second limit is validated — longer mixing with Magnesium Stearate produces a "hyper-lubricated" blend with poor dissolution.',
          output: 'A fixed 60-second blending window is set — sufficient for uniformity without over-lubrication risk.',
          learning: 'Fixed time limits are a GMP control — they prevent well-intentioned operators from running extra mixing cycles "just to be sure," which paradoxically worsens blend quality.',
        },
      },
      {
        key: 'start',
        type: 'start',
        label: 'Start',
        context: {
          what: 'Start the blender. The drum rotates at the set speed, tumbling all components.',
          industry: 'In IBC blending, the blender start is recorded with the number of rotations (not just time) to allow comparisons across different batch sizes during scale-up.',
          output: 'Blending commences. The granule-excipient mixture is being homogenized.',
          learning: 'Modern blending validation uses stratified sampling (taking samples from multiple positions in the blender) and statistical analysis to confirm uniformity — a process called "blend uniformity analysis (BUA)".',
        },
      },
      {
        key: 'monitor',
        type: 'monitor',
        label: 'Monitor',
        field: 'temperature',
        unit: '°C',
        target: 25,
        durationMs: 3000,
        context: {
          what: 'Monitor the blender during operation. Temperature should remain stable (no friction heat from excessive speed).',
          industry: 'Temperature monitoring during blending detects mechanical issues (bearing failure, drive overload) that can contaminate the product with metal particles or heat-degrade the API.',
          output: 'Confirmation that blending is running within the validated thermal range with no mechanical anomalies.',
          learning: 'Even a step as simple as blending has critical monitoring requirements — because pharmaceutical quality assurance means monitoring every step, not just the chemically complex ones.',
        },
      },
      {
        key: 'complete',
        type: 'record',
        label: 'Complete',
        context: {
          what: 'Record the blend completion including actual mix time, rotation count, and any observations about the blend appearance and consistency.',
          industry: 'In-process blend uniformity samples may be taken by the QC department at this point — typically 10 samples from 10 different locations in the blender, tested for API content.',
          output: 'A documented blend record. The final blend is now ready for compression.',
          learning: 'Content uniformity testing of the final blend is the last quality check before the batch enters the tablet press — a failing result stops the entire batch from being compressed.',
        },
      },
      {
        key: 'transfer',
        type: 'complete',
        label: 'Transfer Final Blend',
        context: {
          what: 'Transfer the final blend to the compression machine hopper. This closes the Blending stage.',
          industry: 'In modern facilities the IBC bin containing the final blend is directly docked onto the tablet press hopper — a "gravity feed" system that eliminates manual transfers and contamination risk.',
          output: 'Final blend is confirmed transferred. The Compression Operator station is unlocked.',
          learning: 'The final blend transfer is the gateway to the actual tablet-making process. All the upstream work (dispensing, milling, granulation, drying, blending) now converges into this single stream.',
        },
      },
    ],
  },

  {
    key: 'compression',
    order: 6,
    stageName: 'Compression',
    title: 'Compression Operator',
    icon: 'press',
    summary: 'Compresses the final blend into tablets. Creates the actual product.',
    steps: [
      {
        key: 'receive',
        type: 'info',
        label: 'Receive Final Blend',
        text: 'Final blend received from the blending stage.',
        context: {
          what: 'Accept the formal transfer of the final blend from the Blending stage and verify the accompanying batch documentation before starting tablet pressing.',
          industry: 'The compression operator must verify the blend yield, in-process test results, and the dispensing record before starting — a requirement under 21 CFR Part 211.188(b)(11).',
          output: 'Confirmation that the correct material with the correct documentation is present before starting compression.',
          learning: 'Verification steps before each stage prevent the expensive error of compressing the wrong blend or an out-of-specification blend into 100,000 tablets.',
        },
      },
      {
        key: 'load',
        type: 'load',
        label: 'Load Compression Machine',
        text: 'Load the final blend hopper.',
        context: {
          what: 'Dock the final blend IBC onto the tablet press hopper and begin feeding material to the press.',
          industry: 'Modern rotary tablet presses (e.g., Fette 3090, Korsch XL) can produce up to 500,000 tablets per hour. The feed frame distributes the blend uniformly into the die cavities.',
          output: 'The tablet press hopper is filled and material is flowing into the feed frame.',
          learning: 'Even loading a tablet press is a GMP activity — the hopper must be clean, the IBC verified, and the initial startup tablets (first 100) are discarded as set-up waste.',
        },
      },
      {
        key: 'set_speed',
        type: 'set',
        label: 'Set Machine Speed',
        field: 'speed',
        unit: 'RPM',
        target: 40,
        context: {
          what: 'Set the turret speed (RPM) of the rotary tablet press. This controls how many tablets are produced per minute.',
          industry: 'A 40 RPM turret with 36 punch stations produces ~1440 tablets/minute. Higher speed risks poor die fill and weight variation. The validated maximum speed for this blend is documented in the Process Validation report.',
          output: 'The press turret is set to produce tablets at a controlled rate that ensures adequate die filling time.',
          learning: 'Speed vs. quality is the fundamental trade-off in tablet compression — going too fast sacrifices uniformity to increase throughput.',
        },
      },
      {
        key: 'set_target_weight',
        type: 'set',
        label: 'Set Target Weight',
        field: 'targetWeight',
        unit: 'mg',
        target: 500,
        context: {
          what: 'Set the target tablet weight on the compression machine. The press automatically adjusts the fill depth to achieve this target.',
          industry: 'Tablet weight directly determines drug content (potency). A 500 mg tablet with 500 mg/g API content means every milligram of weight deviation is a milligram of dose deviation.',
          output: 'The press is calibrated to produce tablets of 500 mg ± 10 mg (Ph. Eur. ≤ 2.5% deviation for tablets > 250 mg).',
          learning: 'Weight control is the core of potency control in tablet manufacturing — it is why tablet presses have automatic weight monitoring systems that sample and weigh tablets every 30 seconds.',
        },
      },
      {
        key: 'set_force',
        type: 'set',
        label: 'Set Compression Force',
        field: 'force',
        unit: 'kN',
        target: 8,
        context: {
          what: 'Set the main compression force (kN) applied by the punches to compact the powder into a tablet.',
          industry: 'Compression force directly controls tablet hardness. 8 kN is validated for this blend to produce tablets with 80–120 N hardness — strong enough to survive packaging but friable enough to disintegrate quickly.',
          output: 'Compression force is set at 8 kN, producing tablets with the target hardness for optimal dissolution and mechanical integrity.',
          learning: 'Force-hardness-dissolution is a three-way trade-off. A tablet too hard fails dissolution; too soft fails friability. The validated force is the sweet spot between these failure modes.',
        },
      },
      {
        key: 'start',
        type: 'start',
        label: 'Start',
        context: {
          what: 'Start the tablet press. The rotary turret begins cycling punches through the die cavities, compressing tablets.',
          industry: 'The first 100 tablets from every compression run are weighed and inspected individually and then discarded — these "setup tablets" are produced during machine stabilization.',
          output: 'The tablet press is running. 40 punches are cycling per minute, producing approximately 1440 tablets per minute.',
          learning: 'Startup scrap is a built-in quality control measure. The first tablets always have more variation as the machine stabilizes, so discarding them ensures only quality product is retained.',
        },
      },
      {
        key: 'monitor',
        type: 'confirm',
        label: 'Monitor Tablet Results',
        field: 'actualWeight',
        unit: 'mg',
        compareTo: 'targetWeight',
        tolerancePct: 2,
        context: {
          what: 'Enter the actual average tablet weight measured during the run. The system checks this against the 500 mg target with a ±2% tolerance.',
          industry: 'In-process weight checking by the operator occurs every 30 minutes using a 10-tablet sample weighed on a precision balance. The result is entered into the EBR. Out-of-specification results trigger an immediate press stop.',
          output: 'A documented in-process weight check result. If outside 490–510 mg, a quality alert fires and the QMS system is notified.',
          learning: 'In-process testing is a real-time quality gate. It catches compression problems within 30 minutes rather than after 100,000 tablets have already been produced.',
        },
      },
      {
        key: 'complete',
        type: 'record',
        label: 'Complete',
        context: {
          what: 'Log the compression batch results: total tablets produced, IPC (In-Process Control) results, yield, and any machine stoppages.',
          industry: 'The compression completion report feeds into the Batch Release calculation. A yield below 98% requires a formal investigation before the batch can be released.',
          output: 'A complete compression batch record with all IPC results and the final tablet count.',
          learning: 'Yield calculation at every stage is how the industry performs reconciliation — ensuring that every kilogram of raw material is accounted for as either product, waste, or sample.',
        },
      },
      {
        key: 'transfer',
        type: 'complete',
        label: 'Send Tablets to Coating',
        context: {
          what: 'Transfer the compressed core tablets to the Coating stage for film coating application.',
          industry: 'Tablets are typically stored in polythene-lined stainless steel drums and a minimum sample is retained for reference standards and stability studies.',
          output: 'Core tablets are confirmed transferred. The Coating Operator station is unlocked.',
          learning: 'Retention samples are mandatory — a portion of every batch is stored under controlled conditions for 1 year past expiry, allowing investigation of any future patient complaint.',
        },
      },
    ],
  },

  {
    key: 'coating',
    order: 7,
    stageName: 'Coating',
    title: 'Coating Operator',
    icon: 'spray',
    summary: 'Applies film coating to compressed tablets.',
    steps: [
      {
        key: 'load',
        type: 'load',
        label: 'Load Tablets',
        text: 'Load tablets into the coating pan.',
        context: {
          what: 'Transfer the compressed core tablets into the rotating coating pan.',
          industry: 'Film coating pans (e.g., Glatt Coater, Accela Cota) are validated for specific batch sizes. Overloading reduces coating uniformity; under-loading causes tablet-to-tablet collision damage.',
          output: 'The coating pan is loaded with the correct quantity of tablets, ready for film coat application.',
          learning: 'Coating is both a quality-protective step (moisture barrier, taste masking) and an identity step — the colour of the coating is often the only visual distinction between different strengths of the same drug.',
        },
      },
      {
        key: 'prepare',
        type: 'load',
        label: 'Prepare Coating Material',
        text: 'Prepare the coating suspension.',
        context: {
          what: 'Prepare the aqueous film coating suspension by dispersing the coating polymer (e.g., Opadry II) in purified water and mixing until uniform.',
          industry: 'The coating suspension is prepared to a defined concentration (typically 15–20% w/w solids) and mixed for a defined time to hydrate the polymer completely before use.',
          output: 'A uniform, ready-to-spray coating suspension with the correct solid content and viscosity.',
          learning: 'Coating suspension preparation is a pre-process that must be completed before the pan is loaded — starting with a poorly prepared suspension causes coating defects like orange peel texture and mottling.',
        },
      },
      {
        key: 'set_pan_speed',
        type: 'set',
        label: 'Set Pan Speed',
        field: 'panSpeed',
        unit: 'RPM',
        target: 8,
        context: {
          what: 'Set the rotation speed of the coating pan drum. This controls how tablets tumble and expose all surfaces to the spray.',
          industry: 'Pan speed must be high enough to tumble tablets through the spray zone but low enough to avoid tablet-to-tablet impact breakage. 8 RPM is the validated speed for 500 mg Paracetamol tablets.',
          output: 'The coating pan rotates at 8 RPM, ensuring tablets cascade smoothly through the spray zone for even coat application.',
          learning: 'Pan speed is a critical factor in coating weight gain uniformity — the % RSD of coating weight across 10 randomly sampled tablets must be < 5%.',
        },
      },
      {
        key: 'set_temp',
        type: 'set',
        label: 'Set Temperature',
        field: 'temperature',
        unit: '°C',
        target: 50,
        context: {
          what: 'Set the inlet air temperature. Hot air dries each coating layer as it is applied, preventing tablets from sticking together.',
          industry: 'If the inlet temperature is too low, tablets become sticky (picking) and stick together. Too high and the coating dries before it can spread, causing rough "orange peel" surfaces.',
          output: 'The coating pan is heated to 50°C inlet air — validated to produce smooth, glossy film coats without adhesion problems.',
          learning: 'Coating defects (picking, bridging, peeling) are the most common cause of batch rejection in solid dosage manufacturing. Temperature control is the primary prevention tool.',
        },
      },
      {
        key: 'set_spray',
        type: 'set',
        label: 'Set Spray Rate',
        field: 'sprayRate',
        unit: 'mL/min',
        target: 80,
        context: {
          what: 'Set the suspension spray rate delivered by the peristaltic pump to the atomising spray guns.',
          industry: 'The spray rate and atomising air pressure together determine the droplet size. Correct droplet size ensures the coating lands wet enough to spread but dries before the next layer.',
          output: 'The spray guns are delivering 80 mL/min of coating suspension at validated atomising conditions.',
          learning: 'Spray rate is adjusted during scale-up — a rate validated on a 30 kg lab pan may cause over-wetting on a 300 kg production pan due to the larger spray zone.',
        },
      },
      {
        key: 'set_airflow',
        type: 'set',
        label: 'Set Airflow',
        field: 'airflow',
        unit: 'm3/h',
        target: 900,
        context: {
          what: 'Set the exhaust air volume to maintain the correct drying capacity and pan pressure.',
          industry: 'Exhaust airflow must be balanced against spray rate. Too little exhaust and solvent accumulates in the pan, causing tablets to stick. Too much and coating solvent evaporates before droplets reach tablets.',
          output: 'A balanced airflow of 900 m³/h ensures consistent drying rate matched to the 80 mL/min spray input.',
          learning: 'Coating is a thermodynamic balance problem — energy input (hot air) must equal energy output (evaporation) for each layer, repeated hundreds of times to build up the target coating weight.',
        },
      },
      {
        key: 'start',
        type: 'start',
        label: 'Start',
        context: {
          what: 'Start the coating process. The pan rotates, tablets tumble, and the spray guns begin applying the film coating.',
          industry: 'Coating starts with a pre-heating phase (pan rotates, no spray) to bring tablet temperature to the target inlet temperature before spraying begins. This prevents condensation.',
          output: 'Coating commences. Each rotation brings tablets through the spray zone, building up the target 3% weight gain (% coating).',
          learning: 'Target % weight gain (3% for this product) means the film coat adds 3% of the tablet core weight as coating polymer — calculated from tablet sample weights taken every 30 minutes.',
        },
      },
      {
        key: 'monitor',
        type: 'monitor',
        label: 'Monitor',
        field: 'temperature',
        unit: '°C',
        target: 50,
        durationMs: 3500,
        context: {
          what: 'Monitor the exhaust air temperature throughout coating. This indicates the balance between drying and spray rate.',
          industry: 'Rising exhaust temperature means the spray rate can be increased (more capacity for evaporation). Falling exhaust temperature means reduce spray rate or increase inlet temperature.',
          output: 'Continuous monitoring data confirming the coating process is running in the validated thermodynamic window.',
          learning: 'Exhaust temperature is the primary process feedback signal in coating — experienced operators adjust spray rate in real time based on its value, making coating both a science and an art.',
        },
      },
      {
        key: 'complete',
        type: 'record',
        label: 'Complete',
        context: {
          what: 'Record the final coating weight gain, coating time, and appearance evaluation (colour, gloss, surface uniformity).',
          industry: 'The coating endpoint is determined by achieving the target weight gain (3% for this product). A sample of 20 tablets is weighed to calculate the average and RSD.',
          output: 'A documented coating completion record with weight gain result and visual inspection pass.',
          learning: 'The coating record becomes part of the batch manufacturing record and is reviewed by QA during batch release — any deviation from the validated parameters requires formal justification.',
        },
      },
      {
        key: 'transfer',
        type: 'complete',
        label: 'Send Coated Tablets to Inspection',
        context: {
          what: 'Transfer the finished coated tablets to the Inspection stage for final visual and quality inspection.',
          industry: 'After coating, tablets typically rest for a defined period (equilibration) before inspection to allow the coating to fully dry and harden.',
          output: 'Coated tablets confirmed transferred. The Inspection Operator station is unlocked.',
          learning: 'The equilibration period is a process parameter — it prevents misleading inspection results from soft coatings that would pass immediately after coating but fail after hardening.',
        },
      },
    ],
  },

  {
    key: 'inspection',
    order: 8,
    stageName: 'Inspection',
    title: 'Inspection Operator',
    icon: 'search',
    summary: 'Performs the simulated visual/quality inspection of manufactured tablets.',
    steps: [
      {
        key: 'receive',
        type: 'info',
        label: 'Receive Manufactured Tablets',
        text: 'Coated tablets received from Coating for inspection.',
        context: {
          what: "Accept the formal transfer of coated tablets and review the preceding stages' batch documentation before starting inspection.",
          industry: 'The inspection team reviews all in-process test results from previous stages before beginning final inspection. Any open deviations from earlier stages must be evaluated for impact on inspection criteria.',
          output: 'Confirmation that all upstream batch documentation is complete and the correct material is received.',
          learning: 'Inspection is not just about looking at tablets — it starts with a holistic review of the entire batch history, making the inspector the final guardian of batch quality.',
        },
      },
      {
        key: 'totals',
        type: 'totals',
        label: 'Enter Inspection Totals',
        fields: [
          { key: 'totalTablets', label: 'Total Tablets', unit: 'units', target: 10000 },
          { key: 'rejected', label: 'Rejected', unit: 'units', target: 50 },
        ],
        derivedField: 'defectRate',
        derivedLabel: 'Defect Rate',
        derivedUnit: '%',
        alarmAbovePct: 1,
        context: {
          what: 'Enter the total number of tablets inspected and the number rejected. The system calculates the defect rate percentage.',
          industry: 'Visual inspection in pharmaceutical manufacturing follows AQL (Acceptable Quality Level) sampling plans (ISO 2859-1). A 0.5% AQL requires 100% inspection of high-risk defects (cracks, embedded foreign material).',
          output: 'Defect rate % is calculated. A rate above 1% triggers an alarm and requires a QMS investigation into the root cause.',
          learning: 'Defect rate monitoring tracks the health of the entire upstream manufacturing process. Sudden increases often trace back to equipment wear, parameter drift, or material variability from a specific supplier.',
        },
      },
      {
        key: 'checklist',
        type: 'checklist',
        label: 'Check Inspection Parameters',
        items: [
          { key: 'appearance', label: 'Appearance (no visible defects)' },
          { key: 'weight', label: 'Weight within specification' },
          { key: 'size', label: 'Size / Thickness within specification' },
        ],
        context: {
          what: 'Formally verify each critical quality attribute against its specification using the checklist. Each item must be individually confirmed as PASS before the batch can proceed.',
          industry: 'The inspection checklist mirrors the "Finished Product Specification" — a formal regulatory document that defines every measurable quality attribute of the final product.',
          output: 'A completed inspection checklist with pass/fail for each quality attribute.',
          learning: 'Every item on a pharmaceutical inspection checklist has a specification limit backed by clinical data — the limits are not arbitrary; they define the boundary between "safe medicine" and "potentially harmful product."',
        },
      },
      {
        key: 'report',
        type: 'record',
        label: 'Report Result',
        context: {
          what: 'Record the final inspection summary: total inspected, total rejected, defect rate, and the quality decision (Accept / Reject / Hold).',
          industry: 'The inspection report is reviewed and co-signed by a second QA person before the batch can proceed to packaging — the "four-eye principle" mandated by EU GMP Annex 16.',
          output: "A formally signed inspection report with a quality disposition decision.",
          learning: 'The "four-eye principle" (two-person verification) for critical quality decisions is a universal GMP safeguard. It is the same principle used for batch release in QP (Qualified Person) sign-off.',
        },
      },
      {
        key: 'release',
        type: 'complete',
        label: 'Release Accepted Tablets to Packaging',
        context: {
          what: 'Formally release the accepted tablets to the Packaging stage with the signed inspection report.',
          industry: 'This release is a GMP checkpoint — only tablets meeting all inspection criteria can proceed. Rejected tablets are physically segregated and destroyed with documentation.',
          output: 'Accepted tablets confirmed transferred to Packaging. The Packaging Operator station is unlocked.',
          learning: 'The formal release decision is irreversible — once a batch is released, any subsequent problem discovery requires a formal recall procedure. This is why inspection is the most critical quality checkpoint.',
        },
      },
    ],
  },

  {
    key: 'packaging',
    order: 9,
    stageName: 'Packaging',
    title: 'Packaging Operator',
    icon: 'box',
    summary: 'Packages accepted tablets into final packs.',
    steps: [
      {
        key: 'load',
        type: 'load',
        label: 'Load Tablets',
        text: 'Load accepted tablets into the packaging line.',
        context: {
          what: 'Transfer the inspected and released tablets into the blister packaging or bottle filling machine.',
          industry: 'Packaging lines are GMP-validated for specific primary packaging materials (blister film type, foil type). Changing the packaging material requires re-validation.',
          output: 'The packaging machine hopper is filled and ready for the packaging run.',
          learning: 'Primary packaging (in direct contact with the drug) is part of the product specification — it must protect the tablet from moisture, light, and oxygen throughout the shelf life.',
        },
      },
      {
        key: 'load_material',
        type: 'load',
        label: 'Load Packaging Material',
        text: 'Load blister/pack material.',
        context: {
          what: 'Load the primary packaging materials: PVC/PVDC blister film, aluminium foil lidding, and secondary carton board.',
          industry: 'Packaging materials are released by QC before use — the moisture vapour transmission rate (MVTR) and delamination strength of the blister are tested against specification.',
          output: 'Validated primary packaging materials are loaded into the machine, ready for sealing.',
          learning: 'Packaging failure (blister seal integrity) is the leading cause of tablet moisture degradation and patient complaint. Poor sealing allows ambient moisture in, shortening the shelf life and degrading potency.',
        },
      },
      {
        key: 'set_pack_size',
        type: 'set',
        label: 'Set Pack Size',
        field: 'packSize',
        unit: 'tablets',
        target: 10,
        context: {
          what: 'Set the number of tablets per pack (blister strip). The machine counts tablets as they are filled into each cavity.',
          industry: 'Pack size is defined by the marketing authorisation — it must match the approved product licence exactly. Producing packs of 11 instead of 10 tablets is a GMP violation even if the tablets are correct.',
          output: 'The packaging machine is programmed to produce 10-tablet blister packs.',
          learning: "Packaging specifications are as legally binding as the drug formula itself. The exact pack size, labelling text, and insert leaflet are all part of the product's regulatory approval.",
        },
      },
      {
        key: 'set_speed',
        type: 'set',
        label: 'Set Speed',
        field: 'speed',
        unit: 'packs/min',
        target: 100,
        context: {
          what: 'Set the packaging line throughput speed. This controls how many blister packs are produced per minute.',
          industry: 'At 100 packs/min with 10 tablets/pack, the line produces 1000 tablets/minute — compared to 1440 tablets/minute at the tablet press, showing how packaging is often the production bottleneck.',
          output: 'The packaging line is running at 100 packs/min, the validated maximum speed for this blister format.',
          learning: 'Production bottleneck analysis is how pharmaceutical manufacturers calculate Overall Equipment Effectiveness (OEE) — the packaging line is frequently the constraint that limits overall batch output rate.',
        },
      },
      {
        key: 'start',
        type: 'start',
        label: 'Start',
        context: {
          what: 'Start the packaging line. Tablets flow into blister cavities, foil is sealed over them, blisters are cut, and cartons are filled.',
          industry: 'The first 10 packs from every packaging run are inspected for seal integrity, correct tablet count, print legibility, and pack dimensions — before the line is approved to run.',
          output: 'The full packaging line is running: filling, sealing, cutting, cartoning, and case packing.',
          learning: 'Packaging line startup verification is a GMP requirement — it ensures that label reconciliation, batch number setting, and expiry date printing are all correct before hundreds of thousands of packs are produced.',
        },
      },
      {
        key: 'monitor',
        type: 'totals',
        label: 'Monitor Quantity / Rejections',
        fields: [
          { key: 'produced', label: 'Packs Produced', unit: 'packs', target: 4500 },
          { key: 'packRejected', label: 'Packs Rejected', unit: 'packs', target: 12 },
        ],
        context: {
          what: 'Record the final production totals: packs produced and packs rejected by the online inspection system (check-weigher, vision system).',
          industry: 'Modern packaging lines have 100% automated inspection: check-weighers detect missing tablets, vision systems read barcodes and detect printing defects, seal integrity testers check every blister for leaks.',
          output: 'Final production yield: 4500 packs produced, 12 rejected by automated inspection (0.27% rejection rate).',
          learning: 'Automated 100% inspection in packaging is a PAT application that has virtually replaced traditional sampling plans — it catches every defective pack in real time.',
        },
      },
      {
        key: 'complete',
        type: 'complete',
        label: 'Complete Packaging',
        context: {
          what: 'Formally close the packaging stage and record the final batch yield. This completes all nine manufacturing stages.',
          industry: 'Batch completion triggers the formal Batch Manufacturing Record review by QA. The entire BMR — all 9 stages — is reviewed page by page before the Qualified Person (QP) certifies the batch for release.',
          output: 'The complete batch of Paracetamol 500 mg tablets is manufactured, packaged, and ready for QP certification and distribution.',
          learning: 'The QP release is the final regulatory gate. The QP certifies that the batch was manufactured in accordance with GMP, the approved specification, and the marketing authorisation — a personal legal responsibility.',
        },
      },
    ],
  },
];

// Role 10 - Machine Monitor / Support. Not tied to a single stage;
// described separately since its frontend surface is a dashboard, not
// a step wizard.
const MONITOR_ROLE = {
  key: 'monitor',
  order: 10,
  stageName: null,
  title: 'Machine Monitor / Support',
  icon: 'radar',
  summary: 'Wide-view oversight of every active machine, alarm and operator response across the VM floor.',
  responsibilities: [
    'Watch all active machines and live parameters',
    'See every alarm the moment it fires',
    'Observe whether the assigned operator responds',
    'Offer support / troubleshooting guidance',
    'Verify the event was reported',
    'Escalate if the operator fails to respond',
  ],
};

function getAllRoles() {
  return [...ROLES, MONITOR_ROLE];
}

function getRoleByKey(key) {
  return getAllRoles().find((r) => r.key === key) || null;
}

function getRoleByStageName(stageName) {
  return ROLES.find((r) => r.stageName === stageName) || null;
}

function getRoleByOrder(order) {
  return getAllRoles().find((r) => r.order === order) || null;
}

module.exports = {
  ROLES,
  MONITOR_ROLE,
  getAllRoles,
  getRoleByKey,
  getRoleByStageName,
  getRoleByOrder,
};

